const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
const fs = require('fs');
const path = require('path');
const Analytics = require('../models/Analytics.model');
const SolarPanel = require('../models/SolarPanel.model');
const User = require('../models/User.model');

class ReportService {
  /**
   * Generate PDF Report
   */
  async generatePDFReport(userId, panelId, startDate, endDate, analytics) {
    return new Promise(async (resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const chunks = [];

        doc.on('data', chunk => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));

        // Fetch panel and user details
        const panel = await SolarPanel.findById(panelId).populate('userId');
        const user = await User.findById(userId);

        // Header
        doc.fontSize(24).fillColor('#2563eb').text('Solar Panel Analytics Report', { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).fillColor('#000000').text(`Generated on: ${new Date().toLocaleDateString()}`, { align: 'center' });
        doc.moveDown(2);

        // User and Panel Information
        doc.fontSize(16).fillColor('#1f2937').text('System Information');
        doc.moveDown(0.5);
        this.drawLine(doc);
        doc.fontSize(11);
        doc.text(`Customer: ${user?.name || 'N/A'}`);
        doc.text(`Panel: ${panel?.name || 'Solar Panel'}`);
        doc.text(`Location: ${panel?.location || 'N/A'}`);
        doc.text(`Period: ${new Date(startDate).toLocaleDateString()} - ${new Date(endDate).toLocaleDateString()}`);
        doc.moveDown(2);

        // Energy Production Section
        doc.fontSize(16).fillColor('#1f2937').text('Energy Production');
        doc.moveDown(0.5);
        this.drawLine(doc);
        doc.fontSize(11);
        doc.fillColor('#059669').fontSize(14).text(`${analytics.energyProduced.total.toFixed(2)} kWh`, { continued: false });
        doc.fillColor('#000000').fontSize(11).text('Total Energy Produced');
        doc.moveDown(1);

        // Financial Metrics Section
        doc.fontSize(16).fillColor('#1f2937').text('Financial Metrics');
        doc.moveDown(0.5);
        this.drawLine(doc);
        doc.fontSize(11);
        
        const fm = analytics.financialMetrics;
        doc.text(`Total Savings: ₹${fm.totalSavings.toFixed(2)}`);
        doc.text(`Electricity Tariff: ₹${fm.electricityTariff} per kWh`);
        doc.text(`Maintenance Costs: ₹${fm.maintenanceCosts.toFixed(2)}`);
        doc.text(`Net Savings: ₹${fm.netSavings.toFixed(2)}`);
        doc.fillColor('#059669').text(`ROI: ${fm.roi.toFixed(2)}%`);
        doc.fillColor('#000000').text(`Payback Period: ${fm.paybackPeriod.toFixed(1)} months`);
        doc.moveDown(2);

        // Carbon Footprint Section
        doc.fontSize(16).fillColor('#1f2937').text('Environmental Impact');
        doc.moveDown(0.5);
        this.drawLine(doc);
        doc.fontSize(11);
        
        const cf = analytics.carbonFootprint;
        doc.fillColor('#059669').fontSize(14).text(`${cf.co2Avoided.toFixed(2)} kg CO₂`, { continued: false });
        doc.fillColor('#000000').fontSize(11).text('Carbon Emissions Avoided');
        doc.moveDown(0.5);
        doc.text(`🌳 Equivalent to ${cf.treesEquivalent.toFixed(1)} trees planted`);
        doc.text(`🚗 Equivalent to ${cf.carsOffRoad.toFixed(1)} days of car off road`);
        doc.text(`⚫ Coal avoided: ${cf.coalAvoided.toFixed(2)} kg`);
        doc.moveDown(2);

        // Performance Metrics Section
        doc.fontSize(16).fillColor('#1f2937').text('Performance Metrics');
        doc.moveDown(0.5);
        this.drawLine(doc);
        doc.fontSize(11);
        
        const pm = analytics.performanceMetrics;
        doc.text(`Average Efficiency: ${pm.averageEfficiency.toFixed(2)}%`);
        doc.text(`Peak Power Output: ${pm.peakPowerOutput.toFixed(2)} W`);
        doc.text(`System Uptime: ${pm.systemUptime.toFixed(2)}%`);
        doc.text(`Capacity Factor: ${pm.capacityFactor.toFixed(2)}%`);
        doc.moveDown(2);

        // Footer
        doc.fontSize(9).fillColor('#6b7280').text(
          'This report is automatically generated by Solar Panel Efficiency Optimizer',
          50,
          doc.page.height - 50,
          { align: 'center' }
        );

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Generate Excel Report
   */
  async generateExcelReport(userId, panelId, startDate, endDate, analytics) {
    try {
      const workbook = new ExcelJS.Workbook();
      
      // Fetch panel and user details
      const panel = await SolarPanel.findById(panelId).populate('userId');
      const user = await User.findById(userId);

      // Summary Sheet
      const summarySheet = workbook.addWorksheet('Summary');
      
      // Title
      summarySheet.mergeCells('A1:D1');
      summarySheet.getCell('A1').value = 'Solar Panel Analytics Report';
      summarySheet.getCell('A1').font = { size: 18, bold: true, color: { argb: 'FF2563eb' } };
      summarySheet.getCell('A1').alignment = { horizontal: 'center' };
      
      // System Information
      summarySheet.addRow([]);
      summarySheet.addRow(['System Information']);
      summarySheet.getCell('A3').font = { bold: true, size: 14 };
      summarySheet.addRow(['Customer', user?.name || 'N/A']);
      summarySheet.addRow(['Panel', panel?.name || 'Solar Panel']);
      summarySheet.addRow(['Location', panel?.location || 'N/A']);
      summarySheet.addRow(['Period', `${new Date(startDate).toLocaleDateString()} - ${new Date(endDate).toLocaleDateString()}`]);
      
      // Energy Production
      summarySheet.addRow([]);
      summarySheet.addRow(['Energy Production']);
      summarySheet.getCell('A9').font = { bold: true, size: 14 };
      summarySheet.addRow(['Total Energy Produced', `${analytics.energyProduced.total.toFixed(2)} kWh`]);
      
      // Financial Metrics
      summarySheet.addRow([]);
      summarySheet.addRow(['Financial Metrics']);
      summarySheet.getCell('A12').font = { bold: true, size: 14 };
      summarySheet.addRow(['Total Savings', `₹${analytics.financialMetrics.totalSavings.toFixed(2)}`]);
      summarySheet.addRow(['Electricity Tariff', `₹${analytics.financialMetrics.electricityTariff} per kWh`]);
      summarySheet.addRow(['Maintenance Costs', `₹${analytics.financialMetrics.maintenanceCosts.toFixed(2)}`]);
      summarySheet.addRow(['Net Savings', `₹${analytics.financialMetrics.netSavings.toFixed(2)}`]);
      summarySheet.addRow(['ROI', `${analytics.financialMetrics.roi.toFixed(2)}%`]);
      summarySheet.addRow(['Payback Period', `${analytics.financialMetrics.paybackPeriod.toFixed(1)} months`]);
      
      // Carbon Footprint
      summarySheet.addRow([]);
      summarySheet.addRow(['Environmental Impact']);
      summarySheet.getCell('A20').font = { bold: true, size: 14 };
      summarySheet.addRow(['CO₂ Avoided', `${analytics.carbonFootprint.co2Avoided.toFixed(2)} kg`]);
      summarySheet.addRow(['Trees Equivalent', `${analytics.carbonFootprint.treesEquivalent.toFixed(1)} trees`]);
      summarySheet.addRow(['Cars Off Road', `${analytics.carbonFootprint.carsOffRoad.toFixed(1)} days`]);
      summarySheet.addRow(['Coal Avoided', `${analytics.carbonFootprint.coalAvoided.toFixed(2)} kg`]);
      
      // Performance Metrics
      summarySheet.addRow([]);
      summarySheet.addRow(['Performance Metrics']);
      summarySheet.getCell('A26').font = { bold: true, size: 14 };
      summarySheet.addRow(['Average Efficiency', `${analytics.performanceMetrics.averageEfficiency.toFixed(2)}%`]);
      summarySheet.addRow(['Peak Power Output', `${analytics.performanceMetrics.peakPowerOutput.toFixed(2)} W`]);
      summarySheet.addRow(['System Uptime', `${analytics.performanceMetrics.systemUptime.toFixed(2)}%`]);
      summarySheet.addRow(['Capacity Factor', `${analytics.performanceMetrics.capacityFactor.toFixed(2)}%`]);
      
      // Auto-fit columns
      summarySheet.columns.forEach(column => {
        column.width = 25;
      });

      // Daily Energy Sheet
      if (analytics.energyProduced.daily && analytics.energyProduced.daily.length > 0) {
        const dailySheet = workbook.addWorksheet('Daily Energy Production');
        
        // Headers
        dailySheet.addRow(['Date', 'Energy Produced (kWh)']);
        dailySheet.getRow(1).font = { bold: true };
        dailySheet.getRow(1).fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFE5E7EB' }
        };
        
        // Data
        analytics.energyProduced.daily.forEach(entry => {
          dailySheet.addRow([
            new Date(entry.date).toLocaleDateString(),
            entry.value.toFixed(2)
          ]);
        });
        
        dailySheet.columns.forEach(column => {
          column.width = 20;
        });
      }

      // Return buffer
      const buffer = await workbook.xlsx.writeBuffer();
      return buffer;
    } catch (error) {
      throw new Error(`Excel report generation failed: ${error.message}`);
    }
  }

  /**
   * Helper: Draw horizontal line
   */
  drawLine(doc) {
    doc.moveTo(50, doc.y)
       .lineTo(550, doc.y)
       .strokeColor('#e5e7eb')
       .stroke();
    doc.moveDown(0.5);
  }
}

module.exports = new ReportService();
